#!/bin/bash

cd /project/target

nuget update -self
nuget config -set repositoryPath=/project/packages


if [ packages.config ]; then
    nuget install packages.config
fi

nuget install NUnit.ConsoleRunner -Version 3.6.0
